USE [Impromed]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER DATABASE Impromed SET ENABLE_BROKER;

USE master;
GO
ALTER DATABASE Impromed
    SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE;
GO
USE Impromed;
GO

select * from APPT_M

delete from APPT_M where SERIES_GUID = 'F84F1443-8FB6-409D-A59C-EA85D994F66A'

CREATE TABLE [dbo].[APPT_M](
	[SERIES_GUID] [uniqueidentifier] NOT NULL,
	[CLUSTER_GUID] [uniqueidentifier] NOT NULL,
	[APPT_GUID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[IS_HEADER] [bit] NOT NULL,
	[CLUSTER_DURATION] [bigint] NOT NULL,
	[SERIES_ID] [varchar](50) NOT NULL,
	[PRACTICE_VID] [smallint] NOT NULL,
	[TYPE] [smallint] NOT NULL,
	[STATUS_GUID] [uniqueidentifier] NOT NULL,
	[START_TIME] [datetime] NOT NULL,
	[END_TIME] [datetime] NOT NULL,
	[RESOURCE_GUID] [uniqueidentifier] NOT NULL,
	[PATIENT_GUID] [uniqueidentifier] NOT NULL,
	[WHO_FOR] [smallint] NOT NULL,
	[WHO_FOR_GUID] [uniqueidentifier] NOT NULL,
	[NOTES] [nvarchar](max) NOT NULL,
	[HAS_MULTI_DAYS] [bit] NOT NULL,
	[IS_RECUR] [bit] NOT NULL,
	[CREATE_DATE_TIME] [datetime] NOT NULL,
	[CREATE_OPERATOR_GUID] [uniqueidentifier] NOT NULL,
	[CREATE_WORKSTATION_GUID] [uniqueidentifier] NOT NULL,
	[DELETED] [bit] NOT NULL,
	[PARENT_SERIES_GUID] [uniqueidentifier] NOT NULL,
	[DELETE_FROM_CLUSTER] [bit] NOT NULL,
	[SESSION_GUID] [uniqueidentifier] NULL,
 CONSTRAINT [imp_clpk_APPT_M] PRIMARY KEY CLUSTERED 
(
	[APPT_GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[APPT_M] ADD  CONSTRAINT [DF_APPT_M_SERIES_GUID]  DEFAULT (newid()) FOR [SERIES_GUID]
GO

ALTER TABLE [dbo].[APPT_M] ADD  CONSTRAINT [DF_APPT_ M_APPT_GUID]  DEFAULT (newid()) FOR [APPT_GUID]
GO


