USE master; 
SELECT is_broker_enabled FROM sys.databases WHERE name = 'Impromed';

ALTER DATABASE Impromet SET ENABLE_BROKER;


delete from APPT_M where SERIES_GUID = '69F9A7C7-B744-4E6E-8DFF-D0BE1A0FC24F'

INSERT INTO dbo.APPT_M (SERIES_GUID, CLUSTER_GUID, APPT_GUID, IS_HEADER, CLUSTER_DURATION, 
SERIES_ID, PRACTICE_VID, [TYPE], STATUS_GUID, START_TIME, END_TIME, RESOURCE_GUID, PATIENT_GUID,
WHO_FOR, WHO_FOR_GUID, NOTES, HAS_MULTI_DAYS, IS_RECUR, CREATE_DATE_TIME, CREATE_OPERATOR_GUID,
CREATE_WORKSTATION_GUID, DELETED, PARENT_SERIES_GUID, DELETE_FROM_CLUSTER) 
VALUES (NEWID(), NEWID(), NEWID(), 0, 60, 'Series123', 1, 1, NEWID(), '2024-04-17 08:00:00',
'2024-04-17 09:00:00', NEWID(), NEWID(), 1, NEWID(), 'Example appointment notes', 0, 0,
GETDATE(), NEWID(), NEWID(), 0, NEWID(), 0);
